# Default settings for all events.
defaults:
  # Event priority to listen at.
  # Priorities available: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/EventPriority.html
  priority: NORMAL

  # Minimum interval between logging of each event fire.
  # This is in milliseconds.
  cooldown: 10

# The list of events you want to listen to. You can customise the settings per event if needed.
events:
  - classPath: 'org.bukkit.event.server.ServerLoadEvent'
    priority: NORMAL
    cooldown: 1

  - classPath: 'org.bukkit.event.server.WorldLoadEvent'

  - classPath: 'org.bukkit.event.player.PlayerJoinEvent'
    priority: NORMAL
    cooldown: 1

  - classPath: 'org.bukkit.event.player.PlayerQuitEvent'
    priority: NORMAL
    cooldown: 1
